options:
  channel:
    type: string
    default: 1.18/stable
    description: |
      Snap channel to install kubectl from
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
  tls_warn_days:
    type: int
    default: 60
    description: |
      Number of days left for the TLS certificate to expire before Warning.
  tls_crit_days:
    type: int
    default: 30
    description: |
      Number of days left for the TLS certificate to expire before alerting Critical.
  # temporary config setting for trusted SSL CA (see LP1886982)
  trusted_ssl_ca:
    type: string
    default: ""
    description: |
      base64 encoded SSL ca cert to use for OpenStack API client connections.